"""Initial_migration

Revision ID: 050daaeb1ec1
Revises: 
Create Date: 2026-01-28 01:20:37.611479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050daaeb1ec1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmaker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmaker_key'), 'bookmaker', ['key'], unique=True)
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('external_key', sa.String(), nullable=False),
    sa.Column('internal_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mapping_source_type_external', 'mapping', ['source', 'type', 'external_key'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sports', sa.JSON(), nullable=False),
    sa.Column('bookmakers', sa.JSON(), nullable=False),
    sa.Column('min_edge', sa.Float(), nullable=True),
    sa.Column('min_odds', sa.Float(), nullable=True),
    sa.Column('max_odds', sa.Float(), nullable=True),
    sa.Column('time_window_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sport',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('has_outrights', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_sport_key'), 'sport', ['key'], unique=False)
    op.create_table('league',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('has_outrights', sa.Boolean(), nullable=False),
    sa.Column('sport_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_key'], ['sport.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_league_key'), 'league', ['key'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sport_key', sa.String(), nullable=False),
    sa.Column('league_key', sa.String(), nullable=True),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_key'], ['league.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sport_key'), 'event', ['sport_key'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_key', sa.String(), nullable=False),
    sa.Column('selection', sa.String(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('potential_payout', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmaker.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_event_key', 'market', ['event_id', 'key'], unique=False)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(), nullable=False),
    sa.Column('normalized_selection', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('point', sa.Float(), nullable=True),
    sa.Column('implied_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmaker.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds')
    op.drop_index('ix_market_event_key', table_name='market')
    op.drop_table('market')
    op.drop_table('bet')
    op.drop_index(op.f('ix_event_sport_key'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_league_key'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_sport_key'), table_name='sport')
    op.drop_table('sport')
    op.drop_table('preset')
    op.drop_table('notification')
    op.drop_index('ix_mapping_source_type_external', table_name='mapping')
    op.drop_table('mapping')
    op.drop_index(op.f('ix_bookmaker_key'), table_name='bookmaker')
    op.drop_table('bookmaker')
    # ### end Alembic commands ###
