"""add_popular_to_league

Revision ID: 49ba1e6c39ff
Revises: 7b06fb53ae5f
Create Date: 2026-02-11 14:01:02.138949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ba1e6c39ff'
down_revision: Union[str, Sequence[str], None] = '7b06fb53ae5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('popular', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league', 'popular')
    # ### end Alembic commands ###
