"""Add_Presets_Advanced_Filters

Revision ID: 71fd1f9eae55
Revises: 050daaeb1ec1
Create Date: 2026-01-28 11:58:43.657504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fd1f9eae55'
down_revision: Union[str, Sequence[str], None] = '050daaeb1ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('leagues', sa.JSON(), nullable=True))
    op.add_column('preset', sa.Column('markets', sa.JSON(), nullable=True))
    op.add_column('preset', sa.Column('max_edge', sa.Float(), nullable=True))
    op.add_column('preset', sa.Column('is_live', sa.Boolean(), nullable=False))
    op.add_column('preset', sa.Column('hours_before_min', sa.Integer(), nullable=True))
    op.add_column('preset', sa.Column('hours_before_max', sa.Integer(), nullable=True))
    op.add_column('preset', sa.Column('min_bet', sa.Float(), nullable=True))
    op.add_column('preset', sa.Column('show_all_leagues', sa.Boolean(), nullable=False))
    op.add_column('preset', sa.Column('after_trade_action', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preset', 'after_trade_action')
    op.drop_column('preset', 'show_all_leagues')
    op.drop_column('preset', 'min_bet')
    op.drop_column('preset', 'hours_before_max')
    op.drop_column('preset', 'hours_before_min')
    op.drop_column('preset', 'is_live')
    op.drop_column('preset', 'max_edge')
    op.drop_column('preset', 'markets')
    op.drop_column('preset', 'leagues')
    # ### end Alembic commands ###
