"""add bet_delay_seconds to bookmaker

Revision ID: 792570d62379
Revises: e49adba08c07
Create Date: 2026-01-31 02:06:38.409271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792570d62379'
down_revision: Union[str, Sequence[str], None] = 'e49adba08c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmaker', sa.Column('bet_delay_seconds', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmaker', 'bet_delay_seconds')
    # ### end Alembic commands ###
