"""Add extended odds fields

Revision ID: 7a9ddf292152
Revises: 8daa91083b94
Create Date: 2026-01-29 21:07:34.533201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9ddf292152'
down_revision: Union[str, Sequence[str], None] = '8daa91083b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('url', sa.String(), nullable=True))
    op.add_column('odds', sa.Column('event_sid', sa.String(), nullable=True))
    op.add_column('odds', sa.Column('market_sid', sa.String(), nullable=True))
    op.add_column('odds', sa.Column('sid', sa.String(), nullable=True))
    op.add_column('odds', sa.Column('bet_limit', sa.Float(), nullable=True))
    op.add_column('preset', sa.Column('default_stake', sa.Float(), nullable=True))
    op.drop_column('preset', 'min_bet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('min_bet', sa.FLOAT(), nullable=True))
    op.drop_column('preset', 'default_stake')
    op.drop_column('odds', 'bet_limit')
    op.drop_column('odds', 'sid')
    op.drop_column('odds', 'market_sid')
    op.drop_column('odds', 'event_sid')
    op.drop_column('odds', 'url')
    # ### end Alembic commands ###
