"""Add external_name to mapping

Revision ID: 7b06fb53ae5f
Revises: b0dcd6f2ad1e
Create Date: 2026-02-10 12:14:44.705647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b06fb53ae5f'
down_revision: Union[str, Sequence[str], None] = 'b0dcd6f2ad1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('external_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'external_name')
    # ### end Alembic commands ###
