"""remove potential_payout

Revision ID: 826f453b42c8
Revises: b4201c32630d
Create Date: 2026-01-31 17:25:09.744970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826f453b42c8'
down_revision: Union[str, Sequence[str], None] = 'b4201c32630d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet', 'potential_payout')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('potential_payout', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
