"""add other_config to preset

Revision ID: 8adc565a7612
Revises: b4310ddfc73d
Create Date: 2026-02-01 15:35:40.044984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adc565a7612'
down_revision: Union[str, Sequence[str], None] = 'b4310ddfc73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('other_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preset', 'other_config')
    # ### end Alembic commands ###
