"""add last_sync_at to preset

Revision ID: 8daa91083b94
Revises: c435d0acdf0e
Create Date: 2026-01-28 19:34:14.471885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8daa91083b94'
down_revision: Union[str, Sequence[str], None] = 'c435d0acdf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preset', 'last_sync_at')
    # ### end Alembic commands ###
