"""Rename show_all_leagues to show_popular_leagues

Revision ID: 96715a2531cb
Revises: 49ba1e6c39ff
Create Date: 2026-02-11 15:20:47.376329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Rename show_all_leagues to show_popular_leagues

Revision ID: 96715a2531cb
Revises: 49ba1e6c39ff
Create Date: 2026-02-11 15:20:47.376329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96715a2531cb'
down_revision: Union[str, Sequence[str], None] = '49ba1e6c39ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('show_popular_leagues', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('preset', 'show_all_leagues')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('show_all_leagues', sa.BOOLEAN(), nullable=False, server_default=sa.text('false')))
    op.drop_column('preset', 'show_popular_leagues')
    # ### end Alembic commands ###
