"""add_preset_hidden_items

Revision ID: a2500c1b2e59
Revises: 7a9ddf292152
Create Date: 2026-01-30 10:19:28.355370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2500c1b2e59'
down_revision: Union[str, Sequence[str], None] = '7a9ddf292152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presethiddenitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('market_key', sa.String(), nullable=True),
    sa.Column('selection_norm', sa.String(), nullable=True),
    sa.Column('expiry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['preset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presethiddenitem_event_id'), 'presethiddenitem', ['event_id'], unique=False)
    op.create_index(op.f('ix_presethiddenitem_expiry_at'), 'presethiddenitem', ['expiry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presethiddenitem_expiry_at'), table_name='presethiddenitem')
    op.drop_index(op.f('ix_presethiddenitem_event_id'), table_name='presethiddenitem')
    op.drop_table('presethiddenitem')
    # ### end Alembic commands ###
