"""Add min_probability and max_probability to preset

Revision ID: a9f9345d05ea
Revises: aea040dbb8b2
Create Date: 2026-01-31 00:26:21.634081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f9345d05ea'
down_revision: Union[str, Sequence[str], None] = 'aea040dbb8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('min_probability', sa.Float(), nullable=True))
    op.add_column('preset', sa.Column('max_probability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preset', 'max_probability')
    op.drop_column('preset', 'min_probability')
    # ### end Alembic commands ###
