"""add_balance_to_bookmaker

Revision ID: aea040dbb8b2
Revises: a2500c1b2e59
Create Date: 2026-01-30 12:30:02.524021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea040dbb8b2'
down_revision: Union[str, Sequence[str], None] = 'a2500c1b2e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('bookmaker', sa.Column('balance', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmaker', 'balance')
    # ### end Alembic commands ###
