"""remove bet_delay_seconds from bookmaker

Revision ID: b0dcd6f2ad1e
Revises: 1af73727a616
Create Date: 2026-02-02 20:20:56.560661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dcd6f2ad1e'
down_revision: Union[str, Sequence[str], None] = '1af73727a616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmaker', 'bet_delay_seconds')
    op.drop_column('bookmaker', 'api_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmaker', sa.Column('api_url', sa.VARCHAR(), nullable=True))
    op.add_column('bookmaker', sa.Column('bet_delay_seconds', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###
