"""add_bet_snapshots

Revision ID: b4201c32630d
Revises: 792570d62379
Create Date: 2026-01-31 15:20:40.458566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4201c32630d'
down_revision: Union[str, Sequence[str], None] = '792570d62379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('event_data', sa.JSON(), nullable=True))
    op.add_column('bet', sa.Column('market_data', sa.JSON(), nullable=True))
    op.add_column('bet', sa.Column('odd_data', sa.JSON(), nullable=True))
    op.add_column('bet', sa.Column('payout', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet', 'payout')
    op.drop_column('bet', 'odd_data')
    op.drop_column('bet', 'market_data')
    op.drop_column('bet', 'event_data')
    # ### end Alembic commands ###
