"""add true_odds and margin to odds

Revision ID: c435d0acdf0e
Revises: 71fd1f9eae55
Create Date: 2026-01-28 15:10:02.334322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c435d0acdf0e'
down_revision: Union[str, Sequence[str], None] = '71fd1f9eae55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('true_odds', sa.Float(), nullable=True))
    op.add_column('odds', sa.Column('margin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odds', 'margin')
    op.drop_column('odds', 'true_odds')
    # ### end Alembic commands ###
