"""Add selections filter to preset

Revision ID: e49adba08c07
Revises: ffccf3922c69
Create Date: 2026-01-31 01:55:39.067685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49adba08c07'
down_revision: Union[str, Sequence[str], None] = 'ffccf3922c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('selections', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preset', 'selections')
    # ### end Alembic commands ###
