"""Add auto_trade to preset

Revision ID: ffccf3922c69
Revises: a9f9345d05ea
Create Date: 2026-01-31 01:00:47.724817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffccf3922c69'
down_revision: Union[str, Sequence[str], None] = 'a9f9345d05ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preset', sa.Column('auto_trade', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preset', 'auto_trade')
    # ### end Alembic commands ###
